server:
  port: 8083
spring:
  profiles:
    active: test
person:
  name: qinjiang
  age: 3
  happy: false
  birth: 2000/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  dog:
    name: 旺财
    age: 1

user:
  name: kuangshen
  age: 18
  sex: 男


---
server:
  port: 8084
spring:
  profiles: dev

---
server:
  port: 8085
spring:
  profiles: test
